services:
  # Frontend web service
  - type: web
    name: lcbrn-frontend
    env: static
    buildCommand: npm run build
    staticPublishPath: ./dist
    envVars:
      - key: VITE_API_URL
        value: https://lcbrn-api.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  # Backend API service
  - type: web
    name: lcbrn-api
    env: node
    buildCommand: npm install
    startCommand: node server/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: DB_NAME
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_HOST
        sync: false
      - key: JWT_SECRET
        generateValue: true